### ISSUE TITLE
请问下 pubsub-js 怎么来链接mqtt 服务器啊

### ISSUE THREAD

**Issue by wjm0913** [pangqianjin/everydayHitokoto#1]
请问下 pubsub-js 怎么来链接mqtt 服务器啊

**Comment by pangqianjin** [comment]
pubsub-js只是用于react或者vue的组件间通信的（兄弟组件、子组件向父组件通信等），并不具备链接服务器的功能，我是用的axios这个库来向指定的url发送get/post请求，然后处理得到的数据，至于链接数据库，那是后端的事情，前端不用考虑这些

**Comment by pangqianjin** [comment]
你可以在网上找到一些免费的接口（不用注册，即不用密匙），比如木小果api: api.muxiaoguo.cn，然后直接发送get或者post请求，处理返回的数据就可以了

**Comment by wjm0913** [comment]
o 感谢 我问的有问题！感谢 作者回答！
